theme: just-the-docs

title: 職務経歴書
description: Kazuhiro Hashimoto - 職務経歴書

plugins:
  - jekyll-seo-tag

exclude:
  - tmp
  - Gemfile
  - Gemfile.lock

markdown: kramdown
words_per_minute: 200

color_scheme: light

search_enabled: false

aux_links:
  GitHub:
    - "https://github.com/under-the-bridge-hq"
  LinkedIn:
    - "https://www.linkedin.com/in/under-the-bridge-hq/"
